spring:
  application:
    name: quira-api
  datasource:
    url: jdbc:postgresql://localhost:5432/quiraDB
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

springdoc:
  default-produces-media-type: application/json

server:
  port: 9000
